### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [cimera255/ProtobufMessageFactory#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary protobufmessagefactory -w /tmp/ext protobufmessagefactory==0.1.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting protobufmessagefactory==0.1.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/0a5/a2db9654b4a39/ProtobufMessageFactory-0.1.2.tar.gz (6.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-f1a241pb/protobufmessagefactory/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-f1a241pb/protobufmessagefactory/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-f1a241pb/protobufmessagefactory/pip-egg-info
         cwd: /tmp/pip-wheel-f1a241pb/protobufmessagefactory/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-f1a241pb/protobufmessagefactory/setup.py", line 6, in <module>
        with open("requirements.txt", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by cimera255** [comment]
Added a manifest to the project. 
File "requirements.txt" should now be contained in dist package.

**Comment by thatch** [comment]
Confirmed, thanks!
